name: Build an installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust-target: x86_64-unknown-linux-musl
            os-arch: x86_64
    env:
      CROSS_SYSROOT: /mnt/alpine-${{ matrix.os-arch }}
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-requests musl-tools musl-dev
      
      - name: Do musl workaround
        run: |
          which musl-gcc
          which musl-g++
      
      - name: Get the latest Geode zipball
        run: |
          python3 get-latest-geode.py
      
      - name: Install Rustup targets
        run: rustup target add x86_64-unknown-linux-musl

      - name: Building
        run: |
          cargo build --release --verbose --target x86_64-unknown-linux-musl
    
      - uses: actions/upload-artifact@v4
        with: 
          name: Geode Linux Installer
          path: ./target/x86_64-unknown-linux-musl/release/geode-linux-installer-rs