name: Build an installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install --yes --no-install-recommends musl-tools python3-requests
      
      - name: Do musl workaround
        run: |
          sh -c "which musl-gcc"
          sudo ln -s /usr/bin/musl-gcc /usr/bin/musl-g++
          sh -c "which musl-g++"
      
      - name: Get the latest Geode zipball
        run: |
          python3 get-latest-geode.py
      
      - name: Install Rustup targets
        run: rustup target add x86_64-unknown-linux-musl
      
      - name: Check
        run: cargo check

      - name: Building
        run: |
          cargo build --release --verbose --target x86_64-unknown-linux-musl
    
      - uses: actions/upload-artifact@v4
        with: 
          name: Geode Linux Installer
          path: ./target/x86_64-unknown-linux-musl/release/geode-linux-installer-rs