name: Build an installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust-target: x86_64-unknown-linux-musl
            os-arch: x86_64
    env:
      CROSS_SYSROOT: /mnt/alpine-${{ matrix.os-arch }}
    steps:
      - uses: actions/checkout@v1

      - name: Install Requests for Python
        run: |
          sudo apt-get install python3-requests
      
      - name: Get the latest Geode zipball
        run: |
          python3 get-latest-geode.py

      - name: Building
        run: |
          cargo build --release --verbose

      - uses: actions/upload-artifact@v4
        with: 
          path: ./target/release/geode-linux-installer-rs